# Template C++ Application

# This template allows you to validate your C++ application.
# The workflow allows running tests and code linting on the default branch.

image: irrationalnumbers/fuka:latest
clone:
  enabled: true
  depth: 1

pipelines:
  default:
    - step:
        script: 
          - echo $(`pwd`)
          - echo $BITBUCKET_CLONE_DIR
